version: "3.8"

services:
  mongodb:
    image: mongo:4.4
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=anatolii
      - MONGO_INITDB_ROOT_PASSWORD=otus
    volumes:
      - ./mongo-init/:/docker-entrypoint-initdb.d/:ro

    ports:
      - 27017:27017
      - 9229:9229

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8111:8081
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_MONGODB_ADMINUSERNAME=anatolii
      - ME_CONFIG_MONGODB_ADMINPASSWORD=otus
